# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 19:09
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('meth', django.db.models.manager.Manager()),
            ],
        ),
    ]
